#!/usr/bin/env bash
# Compile the Vulkan quad shaders to SPIR-V and emit C headers with the
# bytecode as uint32_t arrays. Run inside the build container (which has
# glslangValidator). The generated headers are committed so the smoke test
# builds anywhere without a shader compiler.
set -euo pipefail
DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

emit() {
    local src="$1" stage="$2" sym="$3" out="$4"
    glslangValidator -V -S "$stage" "$src" -o /tmp/shader.spv >/dev/null
    {
        echo "// Auto-generated by gen-spirv.sh from $(basename "$src"). Do not edit."
        echo "#pragma once"
        echo "#include <stdint.h>"
        echo "static const uint32_t $sym[] = {"
        od -An -tx4 -v /tmp/shader.spv | awk '{for(i=1;i<=NF;i++) printf "0x%s,", $i}'
        echo
        echo "};"
    } > "$out"
    echo "wrote $out ($(wc -c < /tmp/shader.spv) bytes of SPIR-V)"
}

emit "$DIR/quad.vert" vert quad_vert_spv "$DIR/quad.vert.spv.h"
emit "$DIR/quad.frag" frag quad_frag_spv "$DIR/quad.frag.spv.h"
